version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.4
    - 5.3.5
  - dependency-name: com.github.eirslett:frontend-maven-plugin
    versions:
    - 1.11.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.module:jackson-module-jaxb-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.assertj:assertj-core
    versions:
    - 3.19.0
  - dependency-name: org.jboss.resteasy:resteasy-jaxb-provider
    versions:
    - 4.6.0.Final
  - dependency-name: org.sonarsource.scanner.maven:sonar-maven-plugin
    versions:
    - 3.8.0.2131
  - dependency-name: xerces:xercesImpl
    versions:
    - 2.12.1
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
  - dependency-name: org.jboss.errai.bom:errai-internal-bom
    versions:
    - 4.11.0.Final
  - dependency-name: javax.ws.rs:javax.ws.rs-api
    versions:
    - 2.1.1
  - dependency-name: org.apache.maven.plugins:maven-dependency-plugin
    versions:
    - 3.1.2
  - dependency-name: pl.project13.maven:git-commit-id-plugin
    versions:
    - 4.0.3
  - dependency-name: javax.annotation:javax.annotation-api
    versions:
    - 1.3.2
  - dependency-name: org.springframework.boot:spring-boot
    versions:
    - 2.4.0
  - dependency-name: org.springframework.boot:spring-boot-autoconfigure
    versions:
    - 2.4.0
  - dependency-name: org.springframework.boot:spring-boot-starter-actuator
    versions:
    - 2.4.0
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.0
