version: "3"


services:



  postgres-kie:
    deploy:
      resources:
        limits:
          memory: 1024M
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_DB=chti-data
      - POSTGRES_USER=database_admin
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
      - MAX_CONNECTIONS=500
      - MAX_WAL_SENDERS=100
    volumes:
      - pgsql-data:/var/lib/postgresql/data
      - ./docker/database/:/docker-entrypoint-initdb.d
    ports:
      - 12432:5432




  activemq-server:
    image: webcenter/activemq:5.14.3
    volumes:
      - activemqdata:/data
    ports:
      - 10162:8161
      - 1617:61616
    restart: always


volumes:
  pgsql-data:
  activemqdata:
