version: "3"


networks:
   drools-network:
      ipam:
         config:
            - subnet: 172.27.0.0/24


services:

   kie-wb:
      image: kie-wb
      container_name: "businessCentral"
      volumes:
         - gitdata:/home/niodir
         - lucenedata:/home/lucene
      networks:
         drools-network:
            ipv4_address: 172.27.0.5
      ports:
         - 8080:8080
         - 8001:8001

      restart: always

volumes:
   mongodb:
   mongodb_config:
   gitdata:
   lucenedata:
   esdata2: