version: "3"


networks:
   drools-network:
      ipam:
         config:
            - subnet: 172.27.0.0/24


services:

   kie-wb:
      image: kie-wb
      container_name: "businessCentral"
      volumes:
         - gitdata:/home/niodir
         - lucenedata:/home/lucene
      networks:
         drools-network:
            ipv4_address: 172.27.0.5
      ports:
         - 8080:8080
         - 8001:8001

      restart: always


   admin-console:
      image: runtime-admin-console
      container_name: "admin-console"
      networks:
         drools-network:
            ipv4_address: 172.27.0.6
      ports:
         - 8200:8200
      links:
         - businessProxyDB:mongodb
         - elasticsearchhost
         - kie-wb
      depends_on:
         - businessProxyDB
         - elasticsearchhost
         - kie-wb
      restart: always

   runtime-proxy-1:
      image: runtime-proxy
      container_name: "runtime-proxy-1"
      networks:
         drools-network:
            ipv4_address: 172.27.0.22
      ports:
         - 8090
         - 9080
      links:
         - businessProxyDB:mongodb
         - kie-wb:kie-wb
      depends_on:
         - businessProxyDB
         - kie-wb
      restart: always

   runtime-proxy-2:
      image: runtime-proxy
      container_name: "runtime-proxy-2"
      networks:
         drools-network:
            ipv4_address: 172.27.0.32
      ports:
         - 8090
         - 9080
      links:
         - businessProxyDB:mongodb
         - kie-wb:kie-wb
      depends_on:
         - businessProxyDB
         - kie-wb
      restart: always

   runtime-proxy-3:
      image: runtime-proxy
      container_name: "runtime-proxy-3"
      networks:
         drools-network:
            ipv4_address: 172.27.0.42
      ports:
         - 8090
         - 9080
      links:
         - businessProxyDB:mongodb
         - kie-wb:kie-wb
      depends_on:
         - businessProxyDB
         - kie-wb
      restart: always

   runtime-proxy-4:
      image: runtime-proxy
      container_name: "runtime-proxy-4"
      networks:
         drools-network:
            ipv4_address: 172.27.0.52
      ports:
         - 8090
         - 9080
      links:
         - businessProxyDB:mongodb
         - kie-wb:kie-wb
      depends_on:
         - businessProxyDB
         - kie-wb
      restart: always

   runtime-proxy-5:
      image: runtime-proxy
      container_name: "runtime-proxy-5"
      networks:
         drools-network:
            ipv4_address: 172.27.0.62
      ports:
         - 8090
         - 9080
      links:
         - businessProxyDB:mongodb
         - kie-wb:kie-wb
      depends_on:
         - businessProxyDB
         - kie-wb
      restart: always


   runtime-indexer:
      image: runtime-indexer
      container_name: "runtime-indexer"
      networks:
         drools-network:
            ipv4_address: 172.27.0.23
      links:
         - businessProxyDB:mongodb
         - elasticsearchhost
      depends_on:
         - businessProxyDB
         - elasticsearchhost
      restart: always

   runtime-reverse-proxy:
      image: runtime-reverse-proxy
      container_name: "runtime-reverse-proxy"
      networks:
         drools-network:
            ipv4_address: 172.27.0.25

      links:
         - businessProxyDB:mongodb
      depends_on:
         - businessProxyDB
      ports:
         - 9500:9500

      restart: always





   elasticsearchhost:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
      container_name: "elasticsearchhost"
      ulimits:
         memlock:
            soft: -1
            hard: -1
      volumes:
         - esdata2:/usr/share/elasticsearch/data
      networks:
         drools-network:
            ipv4_address: 172.27.0.7
      ports:
         - 9300:9300
      restart: always

   businessProxyDB:
      image: mongo
      container_name: "businessProxyDB"
      volumes:
         - mongodb:/data/db
         - mongodb_config:/data/configdb
      networks:
         drools-network:
            ipv4_address: 172.27.0.3
      ports:
         - 28017:27017
      command: mongod
      restart: always


volumes:
   mongodb:
   mongodb_config:
   gitdata:
   lucenedata:
   esdata2: